[package]
name = "sgraph"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
pollster = { version = "0.3.0", features = ["macro"] }
wgpu = "0.15.1"
winit = "0.28.1"
